language: java
jdk:
  - oraclejdk8

cache:
  directories:
    - $HOME/.m2

script:
  - mvn package -B

deploy:
  provider: script
  script: mvn deploy -s settings.xml -B -Dbintray=$bintray
  on:
    tags: true